const coaches = [
  {
    id: 1,
    name: "DaGG3r",
    game: "Valorant",
    rank: "Radiant",
    img: "dagg3r.png",
    ingameexp: "Опыт игры 5 лет",
    role: "Все агенты/flex",
    exp: "Более {highlight1} учеников",
    highlight1: "100+",
    highlight2: "T2 сцены, топ-1 в мире по HS%",
    achievements:
      "Профессиональный игрок {highlight2}, участник официальных турниров Riot",
  },
  {
    id: 2,
    name: "Mainrelise",
    game: "Dota 2",
    rank: "9600 MMR",
    img: "mainrelise.png",
    ingameexp: "Опыт игры 10 лет",
    role: "Мидер",
    exp: "Более {highlight1} учеников",
    highlight1: "100+",
    highlight2: "Топ-2 Huskar ",
    achievements:
      "{highlight2} в рейтинге DotaBuff. Имеет серьёзный опыт игры на открытой соревновательной сцене Dota 2",
  },
  {
    id: 3,
    name: "Msdd",
    game: "Valorant",
    rank: "Radiant",
    img: "msdd.jpg",
    ingameexp: "Опыт игры 5 лет",
    role: "(Reyna 2000+ часов), Clove, Killjoy, Sova, Jett",
    exp: "Более {highlight1} учеников",
    highlight1: "100+",
    highlight2: "T3-командах ",
    achievements:
      "Участие {highlight2} и тренировках - Победитель турниров, опыт T3 сцены",
  },
  {
    id: 4,
    name: "Aki",
    game: "Dota 2",
    rank: "9000 MMR",
    img: "aki.png",
    ingameexp: "Опыт игры 9 лет",
    role: "Оффлейн /саппорт /керри",
    exp: "Более {highlight1} учеников",
    highlight1: "300+",
    highlight2: "MONO",
    achievements:
      "Участник турниров от {highlight2} и Discord-сообществ, с опытом выступлений на различных онлайн-турнирах и уверенной игрой на нескольких ролях",
  },
  {
    id: 5,
    name: "Schastie",
    game: "Valorant",
    rank: "Radiant",
    img: "schastie.png",
    ingameexp: "Опыт игры 5 лет",
    role: "Все агенты/flex",
    exp: "Более {highlight1} учеников",
    highlight1: "75+",
    highlight2: "(Reyna 7000+ часов)",
    achievements:
      "{highlight2} Отлично разбирается в механиках дуэлянтов, смокеров и инициаторов, делает упор на индивидуальный скилл",
  },
  {
    id: 6,
    name: "Bewix",
    game: "Valorant",
    rank: "Radiant",
    img: "bewix.png",
    ingameexp: "Опыт игры 5 лет",
    role: "Все агенты/flex",
    exp: "Более {highlight1} учеников",
    highlight1: "30+",
    highlight2: "VRC",
    achievements:
      "Участник Premier и {highlight2}. Универсальный игрок с сильным командным стилем",
  },
  {
    id: 7,
    name: "uncrwndk1ng$",
    game: "Valorant",
    rank: "Radiant",
    img: "king.png",
    ingameexp: "Опыт игры 5 лет",
    role: "Jett, Reyna, Clove, Sova",
    exp: "Более {highlight1} учеников",
    highlight1: "100+",
    highlight2: "T3 сцены, Капитан команды SFU",
    achievements:
      "Бывший игрок {highlight2}, участие в МСКЛЕ (межвузовская студенческая киберспортивная лига)",
  },
  {
    id: 8,
    name: "SacredSixxx",
    game: "Dota 2",
    rank: "7500 MMR",
    img: "sacred.png",
    ingameexp: "Опыт игры 10 лет",
    role: "Оффлейн также играет керри и на 4-й позиции",
    exp: "Более {highlight1} учеников",
    highlight1: "100+",
    highlight2: "топ-200 Европы",
    achievements:
      "Бывший semi-pro игрок, {highlight2} в 2018. Опытный оффлейнер, уверенно играет на керри и саппортах",
  },
  {
    id: 9,
    name: "EarthquakeSoul",
    game: "Dota 2",
    rank: "9000 MMR",
    img: "earthquake.png",
    ingameexp: "Опыт игры 9 лет",
    role: "Оффлейн/Саппорт/Керри",
    exp: "Более {highlight1} учеников",
    highlight1: "40+",
    highlight2: "Топ-3 Earthshaker в 2024",
    achievements:
      "{highlight2}. Участник Moyo Cup (33-е место). Обучает позиционной игре и командной координации",
  },
  {
    id: 10,
    name: "Olin",
    game: "Valorant",
    rank: "Radiant",
    img: "olin.png",
    ingameexp: "Опыт игры 5 лет",
    role: "Jett, Reyna, Clove, Sova",
    exp: "Более {highlight1} учеников",
    highlight1: "140+",
    highlight2: "6000+ часов",
    achievements:
      "{highlight2} в игре, глубокое понимание механик инициаторов и сентинелов, упор на командную игру",
  },
];
export default coaches;
